[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv"]

[phases.install]
cmds = ["python -m venv venv", "source venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["source venv/bin/activate && echo 'skip collectstatic during build'"]

[start]
cmd = "source venv/bin/activate && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn order_app.wsgi:application --bind 0.0.0.0:8080 --timeout 120 --workers 2"