# Generated by Django 5.2.5 on 2025-08-11 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('category', models.CharField(choices=[('coffee', 'コーヒー'), ('tea', '紅茶・緑茶'), ('juice', 'ジュース'), ('smoothie', 'スムージー'), ('other', 'その他')], default='coffee', max_length=20, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='画像')),
                ('is_available', models.BooleanField(default=True, verbose_name='販売中')),
                ('stock', models.IntegerField(default=999, verbose_name='在庫数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='store',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='services',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffholiday',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='storeholiday',
            name='store',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': 'カート',
                'verbose_name_plural': 'カート',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '受付中'), ('preparing', '準備中'), ('ready', '準備完了'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('total_amount', models.IntegerField(verbose_name='合計金額')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='受け取り予定時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='注文')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文アイテム',
                'verbose_name_plural': '注文アイテム',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cart', verbose_name='カート')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'カートアイテム',
                'verbose_name_plural': 'カートアイテム',
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ショップ名')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='営業中')),
                ('open_time', models.TimeField(default='09:00:00', verbose_name='開店時間')),
                ('close_time', models.TimeField(default='21:00:00', verbose_name='閉店時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL, verbose_name='ショップアカウント')),
            ],
            options={
                'verbose_name': 'ショップ',
                'verbose_name_plural': 'ショップ',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.shop', verbose_name='ショップ'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.shop', verbose_name='ショップ'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffHoliday',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreHoliday',
        ),
    ]
