# Generated by Django 5.2.5 on 2025-08-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_remove_service_store_remove_staff_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
    ]
