# Generated by Django 5.2.5 on 2025-08-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'フード'), ('drink', 'ドリンク')], default='drink', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
